const CartActionTypes = {
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    ADD_ITEM: 'ADD_ITEM',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_CART: 'CLEAR_CART'

};

export default CartActionTypes;
